# Generated by Django 4.2.7 on 2024-03-20 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0004_alter_products_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='name',
            field=models.CharField(max_length=150, verbose_name='Name'),
        ),
    ]
